/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as IndexRouteImport } from './routes/index'

const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/players': typeof PlayersRoute
  '/sponsors': typeof SponsorsRoute
  '/tournament': typeof TournamentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/players': typeof PlayersRoute
  '/sponsors': typeof SponsorsRoute
  '/tournament': typeof TournamentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/players': typeof PlayersRoute
  '/sponsors': typeof SponsorsRoute
  '/tournament': typeof TournamentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/players' | '/sponsors' | '/tournament'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/players' | '/sponsors' | '/tournament'
  id: '__root__' | '/' | '/players' | '/sponsors' | '/tournament'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayersRoute: typeof PlayersRoute
  SponsorsRoute: typeof SponsorsRoute
  TournamentRoute: typeof TournamentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayersRoute: PlayersRoute,
  SponsorsRoute: SponsorsRoute,
  TournamentRoute: TournamentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
